name: ama
description: "Single Vendor Ecommerce App"

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
####################### basic ############################
  dartz: ^0.10.1
  dio: ^5.3.2
  get_it: ^7.6.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.2.0
  flutter_offline: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  jwt_decode: ^0.3.1
  flutter_screenutil: ^5.9.0
  page_transition: ^2.0.9
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.2.2
  supercharged: ^2.1.1
  url_launcher: ^6.1.14
  avatar_glow: ^3.0.1
  image_picker: ^1.0.4
  loader_overlay: ^4.0.0
  quickalert: ^1.1.0
  persistent_bottom_nav_bar: ^6.2.1
  pinput: ^5.0.0
  introduction_screen: ^3.1.12
  device_preview: ^1.2.0
  flutter_native_splash: ^2.4.1
  velocity_x: ^4.2.1
  font_awesome_flutter: ^10.7.0
  flex_color_scheme: ^7.3.1
  floating_draggable_widget: ^2.1.5
  flutter_chat_ui: ^1.6.14
  flutter_stripe: ^10.2.0
  shimmer: ^3.0.0
  popup_banner: ^1.0.0
  card_swiper: ^3.0.1
####################### Not used ############################

####################### App ############################




flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  device_preview_screenshot: ^1.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/appicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/appicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/appicon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/en.json
    - assets/translations/ar.json
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300

