name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: 'stable'
          cache: true // 2

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Set up Fastlane
        run: gem install fastlane

      - name: Flutter build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos
